### ISSUE TITLE
Angular 16 Ivy issue

### ISSUE THREAD

**Issue by lano-vargas** [Scandit/datacapture-capacitor-samples#1]
Hi, There are compatibilities issues with Ivy on your **"scandit-sdk-angular": "^3.1.1"** on Angular CLI 16, When I try to serve or build I get the following error:
```
Error: src/app/app.module.ts:68:12 - error NG6002: 'ScanditSdkModule' does not appear to be an NgModule class.

 68   imports: [
               ~
 69     ScanditSdkModule.forRoot(licenseKey, {engineLocation, preloadEngine: true, preloadBlurryRecognition: true}),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
101     MatSnackBarModule
    ~~~~~~~~~~~~~~~~~~~~~
102   ],
    ~~~

  node_modules/scandit-sdk-angular/lib/scandit-sdk.module.d.ts:5:22
    5 export declare class ScanditSdkModule {
                           ~~~~~~~~~~~~~~~~
    This likely means that the library (scandit-sdk-angular) which declares ScanditSdkModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```
**On Angular 15 however still works but there is a message:** 
```
⠸ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
......
- scandit-sdk-angular [es2015/esm2015] ()
......
Encourage the library authors to publish an Ivy distribution.
✔ Browser application bundle generation complete.
```
It looks like you version need some work on the Ivy distribution to work above 15.

This is the version with the issue:
```
Angular CLI: 16.2.11
Node: 18.13.0
Package Manager: npm 9.9.2
```

**Comment by ScanditSupport** [comment]
Hi,

Thanks for reporting this to us.

I have shared the information with our internal team, if this issue is affecting you and would like to have a follow-up on the status of the fix, please reach out to use directly through support@scandit.com describing your issues in detail.

Kind regards,
Raül

**Comment by ScanditSupport** [comment]
Hi @lano-vargas, 

We'd suggest using our new WebSDK 6.x release since it has a lot of improvements added. 
Documentation is available at https://docs.scandit.com/data-capture-sdk/web/index.html. 

A detailed guideline on how to integrate it with Angular can be found here: https://support.scandit.com/hc/en-us/articles/9806991835420-Angular-Using-WebSDK-with-Angular. 

In case you have more detailed questions, please feel free to reach out to us directly:
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
